- .github/workflows/post-merge.yml
- .github/workflows/publish-docs.yml
- autocalibration/docs/toc.rst
- controller/docs/toc.rst
- docs/toc.rst
- percebro/docs/toc.rst
Provide a clear summary of the changes and the context behind them. Describe **what** was changed, **why** it was needed, and **how** the changes address the issue or add value.
> Github workflows to publish component docs

- .github/workflows/post-merge.yml
- .github/workflows/publish-docs.yml
- docs/index.rst
- docs/toc.rst
- docs/user-guide/How-to-configure-a-hierarchy-of-scenes.md
- docs/user-guide/How-to-integrate-cameras-and-sensors.md
- docs/user-guide/How-to-manually-calibrate-cameras.md
- docs/user-guide/How-to-use-3D-UI.md
- docs/user-guide/How-to-use-sensor-types.md
- docs/user-guide/How-to-visualize-regions.md
- docs/user-guide/Overview.md
- docs/user-guide/convert-object-detections-to-normalized-image-space.md
- docs/user-guide/index.rst
- kubernetes/scenescape-chart/README.md
- percebro/docs/user-guide/How-to-add-custom-models.md
- percebro/docs/user-guide/How-to-connect-to-different-input-sources.md
Create dependency order on publishing documentation to avert issue with top-level docs.
> Create dependency order on publishing documentation.

- docs/Makefile
This PR fixes the issues of deploying scenescape with errors at doxygen build stage.
> Fix doxygen build

- sscape/static/js/sscape.js
Provide a clear summary of the changes and the context behind them. Describe **what** was changed, **why** it was needed, and **how** the changes address the issue or add value.
> ITEP-68622: Fix websocket connection to account for host port

- .github/ci_migration.md
- .github/workflows/migration-tests.yml
- Makefile
Define runPrformanceTests() into Make target.
Trigger performance tests from GitHub Actions workflow.
- [ x ] 🔍 PR title is clear and descriptive
- [ x ] 📝 For internal contributors: If applicable, include the JIRA ticket number (e.g., ITEP-123456) in the PR **title**. Do **not** include full URLs
- [ x ] 💬 I have commented my code, especially in hard-to-understand areas
- [ x ] 📄 I have made corresponding changes to the documentation
> Migration performance tests stage into GitHub Actions

- manager/src/django/views.py
fix: preserve (0,0) sensor coordinates for SingletonSensor calibration
Prevents automatic resetting of sensor_x and sensor_y to map center when set to (0,0)
Ensures correct handling and display of (0,0) coordinates in calibration view and metadata
Resolves SAIL-3606: Inconsistent origin point for sensor coordinates in UI and metadata
- ✅ 🐞 **Bug fix** – Non-breaking change which fixes an issue
- [*] ✅ Tested manually
- ✅ 🔍 PR title is clear and descriptive
> ITEP-17770: Preserve (0,0) sensor coordinates for SingletonSensor calibration

- .github/ci_migration.md
Track the progress of CI migration.
> Update migration tracker

- scene_common/src/scene_common/mqtt.py
Regex is secure based on security expert recommendations in mqtt.py
> ITEP-17759: regex is secure in mqtt.py

- Makefile
- deploy.sh
- dlstreamer-pipeline-server/README.md
- sample_data/docker-compose-dl-streamer-example.yml
Done in this PR:
- Added `demo-dls` make target for running DLStreamer-based demo
- Added support for running DLStreamer-based demo in `deploy.sh`
- Missing autocalibration secret added to DLStreamer docker compose example file
- Added UID and GID env vars automatically by `make demo` target to `.env` file 
- Fixed the issue that volumes are not removed when `./docker-compose.yml` is missing (e.g. subsequent `make clean-all` resulted in error)
- Updated documentation
As a result, UX/DX is improved: now the user can just use commands `make demo` (with Percebro) and `make demo-dls` (with DLStreamer) interchangeably to run the demo.
Before submitting the PR, ensure the …
> ITEP-70140 Improve UX/DX of running DLStreamer-based demo

- manager/config/000-default.conf
Fixes broken Admin UI
Fixes #73 
> ITEP-70563: Fix Broken Admin UI

- Makefile
Fixed issue when prettier-write was always called after prettier-check
> [CI] Changed quote type in `make prettier-check` to disable executing write automatically

- tests/Makefile
> [ITEP-71935] [CI/CD] Extend BAT tests scope

- .github/workflows/lint.yml
This changes optional linters job to always get "pass" status. This should make it more clear if PR can be merged based on status.
> ITEP-70236 Set optional linters job to pass even if steps are failing

- .github/workflows/checks-and-scans.yml
- .github/workflows/post-merge-checks-and-scans.yml
> [CHORE] Bump trivy version

- docs/user-guide/Getting-Started-Guide.md
- docs/user-guide/How-to-inference-using-NVIDIA-gpu-with-OVMS.md
- docs/user-guide/How-to-inference-using-Nvidia-gpu-with-OVMS.md
- docs/user-guide/system-requirements.md
Update the recommended host OS version in documentation.
> ITEP-72395: Update host OS version in documentation

- docs/user-guide/Getting-Started-Guide.md
After changing the file name to the NVIDIA on OVMS doc, we missed updating the link in the GSG. This resolves the issue.
Fixes #ITEP-72397
Closes #ITEP-72397
If referencing an internal ticket (e.g. JIRA), include the ticket number instead:
JIRA: ITEP-72397
> ITEP-72397: Update link to NVIDIA document from GSG

- docs/user-guide/index.rst
Update index.rst with new file name to fix docs build.
Fixes #ITEP-72397
Closes #ITEP-72397
> ITEP-72397: Update link to NVIDIA document in index.rst

- .gitignore
- manager/src/django/models.py
- tests/functional/tc_api_large_strings.py
- tests/security/system/negative_mqtt_insecure_cert.py
- tests/system/stability/tc_sscape_stability.py
Fix CodeQL found issues in tests.
> ITEP-71912: Remove printing of password in tests

- controller/requirements-runtime.txt
- controller/src/controller/scene_controller.py
- controller/src/controller/tools/analytics/library/json_helper.py
- controller/src/controller/tools/analytics/robot
- controller/src/controller/tools/analytics/trackrate
- controller/tools/tracker/tracker
- controller/tools/tracker/tracker-test
Replace json with orjson for faster operation.
> ITEP-72198: replace json with orjson for faster operation

- manager/src/static/js/marks.js
- manager/src/static/js/sscape.js
Show trails is re-enabled.
Click on "Show trail" toggle button on a Scene home page. Observe that the tracks have a trail.
> ITEP-72545: Fix show trails

- .github/workflows/weekly-build.yml
- controller/requirements-runtime.txt
> [ITEP-72775] [Bug Fix] Add .trivyignore

- .github/resources/requirements.txt
- .github/workflows/tests-all.yml
- .github/workflows/tests-bat.yml
Fix All Tests Workflow
This PR fixes issues and improves efficiency in the All Tests Workflow by adding concurrency controls and updating dependencies. The changes aim to reduce CI costs and resolve dependency conflicts.
Added concurrency controls to prevent multiple workflow runs per PR/branch
Updated PyYAML dependency specification to resolve version conflicts
> [ITEP-71797] Fix All Tests Workflow

- .github/workflows/weekly-build.yml
This PR adds parsing logic for release candidate (RC) versions from version.txt file in the build workflow. It modifies the weekly build workflow to handle RC versions differently by using the version.txt content directly as the image tag when it contains "rc".
Key Changes:
- Added error handling when version.txt file is not found
- Added conditional logic to detect RC versions and use them directly as image tags
- Modified existing tag generation logic to accommodate RC version handling
> [ITEP-68209] Add parsing of version.txt for rc version for build

- .github/workflows/weekly-build.yml
- autocalibration/Dockerfile
- controller/Dockerfile
- manager/Dockerfile
- version.txt
[ITEP-68209] Add images description + change publishing repo.
This PR adds Docker image metadata labels and updates the publishing repository for container images. The changes ensure proper image documentation and redirect publishing from the current repository to the open-edge-platform/edge-ai-libraries repository.
Adds standardized OCI labels (description, vendor, licenses, source, documentation) to all Dockerfiles
Updates GitHub Actions workflow to publish images to ghcr.io/open-edge-platform/edge-ai-libraries instead of the current repository
> [ITEP-68209] Add images description + change publishing repo

- manager/src/django/views.py
- tests/Makefile
- tests/Makefile.sscape
- tests/sscape_tests/account-security/pytest.ini
- tests/sscape_tests/cam/pytest.ini
- tests/sscape_tests/singleton_sensor/pytest.ini
- tests/sscape_tests/views/conftest.py
Fix views-unit, account-security-unit, cam-unit and singleton-sensor-unit
> ITEP-73273: Fix unit tests

- tests/Makefile
- tests/Makefile.functional
- tests/Makefile.user_interface
- tests/ui/common_ui_test_utils.py
- tests/ui/tc_calibrate_all_sensor_types.py
- tests/ui/tc_sensor_area.py
- tests/ui/tc_superuser_crud_operations.py
This PR fixes:
1. 3d-camera-control-panel
2. calibrate-all-sensor-types
3. delete-roi-mqtt
4. delete-tripwire-mqtt
5. delete-sensor-mqtt
6. delete-sensor-scene
7. delete-sensors
8. restricted-media-access
9. sensor-area
10. sensor-location
Output from running` make -C tests ui-tests` [out.txt](https://github.com/user-attachments/files/21553881/out.txt)
Provide a clear summary of the changes and the context behind them. Describe **what** was changed, **why** it was needed, and **how** the changes address the issue or add value.
> ITEP-73272: Fix broken UI tests

- autocalibration/requirements-runtime.txt
- autocalibration/src/markerless_camera_calibration_controller.py
- autocalibration/src/polycam_to_images.py
- autocalibration/src/reloc/requirements.txt
- controller/src/controller/scene.py
Pin the pycolmap version to overcome SIFT errors. Pin numpy version to overcome ABI incompatibility for pycolmap compiled against Numpy 1.x C API , other potential changes including memory layout (vstack, array) and buffer lifetime.  
Steps to verify:
- Bring OOB SceneScape.
- Upload markerless polycam zip file as scene map for Queuing scene in scene update page. Save Scene.
- Go to cam calibrate page of either cameras in Queuing scene. Observe that scene registration starts and completes successfully in sometime, with a tooltip indicating to proceed to 3D view for localize.
- Go to 3D view of Queuing scene. toggle project_frame for atag-qcam1 and observe the camera pose …
> ITEP-68814: Fix markerless camera calibration

- manager/config/default-ssl.conf
The frontend code attempts to connect to both WebSocket ports - secure and insecure (1884 and 9001) - using Promises and awaits **both** responses.
In normal environments (e.g., Docker), if no listener is present, the connection is refused immediately with ECONNREFUSED. No retries are made, and the Promises resolve quickly.
In Kubernetes, however, the behavior changes. The connection is routed to the Service IP by kube-proxy, which forwards it to one of the matching Pod IPs. If the container isn't actually listening on the specified port, the kernel might silently drop the packet instead of refusing the connection. `kube-proxy` does not validate whether the port is open.
As a result, the client's TCP stack retries the connection multiple times with exponential backoff, leading to a long …
> ITEP-72774 - Add Apache timeout to prevent long delays when WebSocket backend doesn't listen on port

- .github/resources/coverity-requirements.txt
- .github/resources/requirements.txt
- .github/workflows/auto-update.yml
- .github/workflows/checks-and-scans.yml
- .github/workflows/codeql.yml
- .github/workflows/lint.yml
- .github/workflows/post-merge.yml
- .github/workflows/pre-merge.yml
- .github/workflows/publish-docs.yml
- .github/workflows/weekly-build.yml
- kubernetes/init-images/Dockerfile-models
This PR updates various dependencies and external action references to their latest versions, following standard Dependabot maintenance practices. The changes include Python package version updates, Docker base image upgrades, and GitHub Actions dependency updates.
- Updates Python runtime from 3.12 to 3.13 in Docker images
- Updates multiple GitHub Actions to latest versions for security and bug fixes
- Updates Python package dependencies including pip, wheel, pybind11, and xmltodict
> Dependabot updates

- kubernetes/scenescape-chart/templates/queuing-dep.yaml
- kubernetes/scenescape-chart/templates/retail-dep.yaml
Adds initContainer to check if MQTT port is open before starting dlstreamer container.
> Wait for MQTT init container

- docs/user-guide/Getting-Started-Guide.md
Provide a clear summary of the changes and the context behind them. Describe **what** was changed, **why** it was needed, and **how** the changes address the issue or add value.
Copy of #299 
> ITEP-74093: Improvements to content flow in Getting Started Guide

- .github/resources/sdl/trivy_config.yml
- .github/workflows/trivy.yml
* Updated list of ignored files for trivy scan
* Removed `trivy config` scan as it's duplicated by `trivy filesystem` scan with `misconfig` scanner enabled
> [CI] Improve Trivy scanning

- .github/workflows/auto-update.yml
- .github/workflows/bandit.yml
- .github/workflows/clamav.yml
- .github/workflows/docs-post-merge.yml
- .github/workflows/docs-pre-merge.yml
- .github/workflows/gitleaks.yml
- .github/workflows/lint.yml
- .github/workflows/publish-docs.yml
- .github/workflows/weekly-build.yml
Bumping orch-ci to version 0.1.42
> Orch-ci actions update

- manager/src/static/js/assetmanager.js
- manager/src/static/js/scenescape3d.js
This PR applies object library changes in 3D UI without having to refresh the web page
How to test:
On a different tab update the object library person category color. Observe in the 3D view the tracked objects changes color without the page needing to be refreshed.
> ITEP-73725: change in object library reflect without refreshing the 3D UI web page

- broker/Dockerfile
This PR fixes building of broker image. The build is failing because external dependency has been modified.
> Fix: Update LWS version to `4.3.3` in `broker/Dockerfile`

- dlstreamer-pipeline-server/user_scripts/gvapython/sscape/sscape_3d_detector.py
- docs/user-guide/How-to-run-LPR-with-3D-object-detection.md
- kubernetes/scenescape-chart/values.yaml
- sample_data/docker-compose-dl-streamer-example.yml
- sample_data/docker-compose-dls-perf.yml
- tests/compose/dlstreamer/queuing_video.yml
- tests/compose/dlstreamer/queuing_video_no_ntp.yml
- tests/compose/dlstreamer/queuing_video_reid.yml
- tests/compose/dlstreamer/retail_video.yml
- tests/compose/dlstreamer/retail_video_no_ntp.yml
- tests/compose/dlstreamer/retail_video_reid.yml
- tests/perf_tests/compose/docker-compose-inference_performance.yml
Update `dlstreamer-pipeline-server` version tag to `3.1.0` in Docker and Kubernetes deployments to use the latest public image, including tests and docs.
Using lazy import of `scipy` for 3D detector as `dlstreamer-pipeline-server` base image lacks `scipy` installed. For 3D detection the user is informed to use the extended image in the user documentation.
Changes the healthchecks from using `wget` to `curl` as `wget` is not available in the image.
> Update `dlstreamer-pipeline-server` version tag to `3.1.0`

- autocalibration/Dockerfile
- autocalibration/src/camcalibration-init
- controller/Dockerfile
- controller/src/controller-init
- manager/Dockerfile
- manager/Makefile
- manager/config/webserver-init
- tools/authsecrets/Makefile
- tools/certificates/Makefile
Main processes of `webserver`, `camcalibration` and `controller` containers are running as non-root user. This is needed to fulfil the recommendation from PSE and Security Champion to reduce the attack surface to the extent possible in the release timeframe.
Evindence:
```
docker exec scenescape-camcalibration-1 ps -A -o pid,user,uid,gid,comm
PID USER       UID   GID COMMAND
1 root         0     0 docker-init
7 root         0     0 camcalibration-
31 root         0     0 bindfs
38 root         0     0 bindfs
39 scenesc+  1000  1000 python3
41 root         0     0 tail
174 root         0     0 ps
```
```
docker exec scenescape-scene-1 ps -A -o pid,user,uid,gid,comm
PID USER       UID   GID COMMAND
1 root         0     0 docker-init
7 root         0     0 controller-init
13 scenesc+   999 …
```
> ITEP-74690 Run main processes in production containers as non root

- tests/compose/dlstreamer/broker.yml
- tests/compose/dlstreamer/queuing_video.yml
- tests/compose/dlstreamer/queuing_video_no_ntp.yml
- tests/compose/dlstreamer/queuing_video_reid.yml
- tests/compose/dlstreamer/retail_video.yml
- tests/compose/dlstreamer/retail_video_no_ntp.yml
- tests/compose/dlstreamer/retail_video_reid.yml
Reverts #296 merged accidentally.
> Revert ITEP-74692: Fix volumes for DLStreamer pipeline server on tests compose files #296

- .github/workflows/docs-build.yml
- .github/workflows/docs-publish.yml
> Renamed workflows names

- controller/Dockerfile
- manager/Dockerfile
Update Docker files docs links
This PR updates Docker container metadata to fix incorrect documentation links and standardize service descriptions across the SceneScape project.
Updates Docker image labels to correct documentation URLs pointing to the proper user guide locations
Standardizes the service description format to include possessive form ("SceneScape's")
> [ITEP-74149] Update Dockerfiles docs links

- .github/workflows/docs-publish.yml
Update publish-documentation version
> [main] Update publish-documentation workflow

- Makefile
- dlstreamer-pipeline-server/queuing-config.json
- dlstreamer-pipeline-server/retail-config.json
- sample_data/docker-compose-dl-streamer-example.yml
The following issues reported by DBS scan are addressed in this PR:
- Ensure that privileged containers are not used 
- Ensure Content trust for Docker is Enabled 
- Ensure that only needed ports are open on the container 
- Ensure that the PIDs cgroup limit is used 
> Fix Docker Bench Security warnings

- manager/src/static/js/cameracalibrate.js
- tests/ui/tc_camera_intrinsics.py
This PR fixes a camera calibration viewport issue where image projection was incorrect when image resolution changed, and also fixes a related test. The changes ensure the camera calibration viewport properly updates when resolution changes and that the test correctly handles disabled form elements.
Adds resolution update detection to trigger viewport recalibration
Updates test to check for both readonly and disabled form elements to prevent interaction failures
Steps to verify:
1. 
- Run camera intrinsics test : `cd tests && make camera-intrinsics`
2.
Before:
- OOB queuing camera cam_calibrate page of qcam1, observe that the image projection was incorrect.
- When camera is calibrated manually or using auto calibrate the projection is correct.
- On refreshing the page the projection is …
> ITEP-74942: Update in image resolution reflects in viewport of camera calibration

- scene_common/src/transform.py
Always return valid rotation from rotationToTarget to prevent NoneType errors
> ITEP-74992: Return valid rotation from rotationToTarget

- third-party-programs.txt
The file `third-party-programs.txt` is updated to reflect 1.4.0 release 3rd party software dependencies that are distributed along with their licenses.
> Update `third-party-programs.txt` file

- .github/workflows/docs-publish.yml
Remove auto publish as it may break docs unexpectedly as more release branches will be created
> Remove auto docs publish

- .github/workflows/clean-runner.yml
- .github/workflows/tests-all.yml
- .github/workflows/tests-bat.yml
Added schedule for cleanup job that wasn't ported from release branch.
Added test volumes cleaning after stopping test containers
> Add scheduled cleanup and add volume cleaning

- autocalibration/requirements-runtime.txt
Remediate security alert - https://github.com/open-edge-platform/scenescape/security/dependabot/14 
This PR updates PyTorch and TorchVision dependencies to address a security vulnerability identified by Dependabot. The update moves from PyTorch 2.7.1 to 2.8.0 and TorchVision from 0.22.1 to 0.23.0, both using CPU-only builds.
Updated PyTorch from version 2.7.1+cpu to 2.8.0+cpu
Updated TorchVision from version 0.22.1+cpu to 0.23.0+cpu
> [Dependabot Security Alerts] Update PyTorch

- manager/src/django/api.py
- manager/src/django/views.py
- tests/Makefile.functional
Missing import needed by scene import after moving functionality to api.py
> ITEP-77590: Add missing import for scene import

- .github/workflows/tests-bat.yml
This PR adds the `ready_for_review` event type to the BAT workflow trigger, enabling automated tests to run when a draft PR is marked as ready for review.
- Added `ready_for_review` to the pull request event types in the BAT workflow
> [ITEP-76868] Add ready_for_review PR type to trigger BAT

- tests/Makefile.functional
- tests/Makefile.user_interface
- tests/compose/camcalibration.yml
- tests/compose/web.yml
- tests/runtest
This PR updates tests that use video services to include cams.yml since they depend on it. 
> ITEP-77591: Add missing cams.yml for test video services

- .github/CODEOWNERS
Leaving only common repo owners, removing specific docs owners.
> Remove specific codeowners of docs

- manager/requirements-runtime.txt
This PR fixes HIGH Vulnerability alert appeared on - https://github.com/open-edge-platform/scenescape/actions/runs/17789431857/job/50563062563 
Vulnerability description: https://avd.aquasec.com/nvd/2025/cve-2025-57833/
> [ITEP-77751] [FIX] Bump Django version on manager to fix CVE-2025-57833

- tests/functional/tc_scene_import_api.py
The test was failing in CI due to tiny differences in floating-point values (e.g., -6.164372738166769 vs -6.164372738166768) when comparing expected and actual camera data. These differences are common across platforms due to variations in test environment.
This PR changes strict comparisons of floating-point values to use pytest.approx for slightly more tolerant comparison.
> Fix tc_scene_import_api.py

- .github/resources/sdl/.trivyignore.yaml
- .github/resources/sdl/trivy_config.yml
- .github/workflows/docker-bench-security.yaml
- .github/workflows/trivy.yml
* Removed upload of Trivy and DBS artifacts in CI
* Changed Trivy output format for easier reading on Github
* Removed non-high/critical Trivy scanning
- [*] N/A No changes in code
> Limited artifacts uploaded from CI

- tests/Makefile
This PR moves the sensor-area test from the UI test suite to the broken tests category, indicating that this test is currently failing and should not be run as part of the regular test suite.
- Moved sensor-area test from _ui-tests target to broken-tests target
> [ITEP-78851] Move sensor-area to broken tests
